### ISSUE TITLE
Missing Fis ImageStream

### ISSUE THREAD

**Issue by alekonkoisp** [jbossdemocentral/coolstore-microservice#59] opened 2017-05-28 10:00 UTC
Using new minishift cluster,  Coolstore-gw doesn't compile for missing fuse image stream.

Fixed with 
oc create -f https://raw.githubusercontent.com/jboss-fuse/application-templates/master/fis-image-streams.json -n openshift

is it correct?

bye
Ale

**Comment by DuncanDoyle** [comment] 2017-06-02 13:26
I think this is correct (at least that's how I do it as well). There is another issue with somewhat the same question, so I'll close this. Duplicate of #58

**Closed by DuncanDoyle** 2017-06-02 13:26 UTC
