### ISSUE TITLE
Web ui needs to be refreshed before it shows the products

### ISSUE THREAD

**Issue by siamaksade** [jbossdemocentral/coolstore-microservice#24] opened 2017-01-15 13:42 UTC

**Comment by siamaksade** [comment] 2017-01-17 17:22
@jamesfalkner @tqvarnst

**Comment by siamaksade** [comment] 2017-01-18 10:23
After showing the products, still more refreshes needed to show the correct product inventory

**Comment by siamaksade** [comment] 2017-02-22 12:15
It's also in master branch. I used the provisioning script to deploy the demo

**Comment by siamaksade** [comment] 2017-05-24 04:39
This issue happens deterministically on any of the stable branches as well as in RHPDS.

**Comment by tqvarnst** [comment] 2017-05-25 09:41
I believe I've identified the issue for this. The problem is that the first request takes longer then normal and triggers the circuit breaker. The default timeout is 1000 ms which is kind of low, but it's hard to know exactly what to set the timeout to. I've decided to go for the the following values.

`
.hystrixConfiguration()                      
    .executionTimeoutInMilliseconds(5000).circuitBreakerSleepWindowInMilliseconds(10000)
.end()
`
If this issue occurs again we might have to trim this value.

I will close this issue when I issue the pull request.

**Comment by tqvarnst** [comment] 2017-05-26 11:23
This should now be fixed and has been verified in master, 1.0.x, ocp-stable-3.5.

**Closed by tqvarnst** 2017-05-26 11:23 UTC
